builders:
  de_ser_tree:
    import: "package:mappa_operis/services/json/json.dart"
    builder_factories: ["enumerationTreeBuilder"]
    build_to: source
    build_extensions: { ".dart": [".should_not_generate_output.dart"] }
    auto_apply: root_package
    applies_builders: ["source_gen:combining_builder"]
    runs_before: ["mappa_operis:type_map_imports"]